### ISSUE TITLE
Lua scripting

### ISSUE THREAD

**Issue by rafis** [wilkenstein/redis-mock-js#14]
Now I need Lua scripting more than server mode, for writing tests :)

```
C:\project\node_modules\node-redis-scripty\lib\Scripty.js:40
  redis.script('load', src, function(err, redisDigest) {
        ^

TypeError: redis.script is not a function
    at Scripty.loadScript (C:\project\node-redis-scripty\lib\Scripty.js:40:9)
    at C:\project\node_modules\node-redis-scripty\lib\Scripty.js:72:17
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

I've tried to use [kue](https://github.com/Automattic/kue) and it uses [this Lua script](https://raw.githubusercontent.com/TheDeveloper/warlock/v0.1.4/lib/lua/parityDel.lua).

**Comment by rafis** [comment]
I have switched to [mock-kue](https://github.com/raweng/mock-kue). For simple tasks it is working.
